version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    command: npm install && npm run start:dev  # Ensure dependencies are installed in the container
    networks:
      - my_network
    stdin_open: true
    tty: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    command: npm install && npm start  # Ensure dependencies are installed in the container
    networks:
      - my_network
    stdin_open: true
    tty: true
    depends_on:
      - backend

networks:
  my_network:
